
INSERT INTO Movie (title, genre, director, actors, year, runtime, imdb) VALUES
('Inception', 'Sci-Fi', 'Christopher Nolan', 'Leonardo DiCaprio, Joseph Gordon-Levitt', '2010', '148 min', '8.8'),
('The Godfather', 'Crime', 'Francis Ford Coppola', 'Marlon Brando, Al Pacino', '1972', '175 min', '9.2'),
('The Dark Knight', 'Action', 'Christopher Nolan', 'Christian Bale, Heath Ledger', '2008', '152 min', '9.0'),
('Pulp Fiction', 'Crime', 'Quentin Tarantino', 'John Travolta, Uma Thurman', '1994', '154 min', '8.9'),
('Schindler's List', 'Drama', 'Steven Spielberg', 'Liam Neeson, Ralph Fiennes', '1993', '195 min', '9.0'),
('Forrest Gump', 'Drama', 'Robert Zemeckis', 'Tom Hanks, Robin Wright', '1994', '142 min', '8.8'),
('Fight Club', 'Drama', 'David Fincher', 'Brad Pitt, Edward Norton', '1999', '139 min', '8.8'),
('The Matrix', 'Sci-Fi', 'The Wachowskis', 'Keanu Reeves, Laurence Fishburne', '1999', '136 min', '8.7'),
('The Lord of the Rings: The Fellowship of the Ring', 'Fantasy', 'Peter Jackson', 'Elijah Wood, Ian McKellen', '2001', '178 min', '8.8'),
('The Shawshank Redemption', 'Drama', 'Frank Darabont', 'Tim Robbins, Morgan Freeman', '1994', '142 min', '9.3'),

('Interstellar', 'Sci-Fi', 'Christopher Nolan', 'Matthew McConaughey, Anne Hathaway', '2014', '169 min', '8.6'),
('The Prestige', 'Mystery', 'Christopher Nolan', 'Christian Bale, Hugh Jackman', '2006', '130 min', '8.5'),
('Gladiator', 'Action', 'Ridley Scott', 'Russell Crowe, Joaquin Phoenix', '2000', '155 min', '8.5'),
('The Lion King', 'Animation', 'Roger Allers, Rob Minkoff', 'Matthew Broderick, Jeremy Irons', '1994', '88 min', '8.5'),
('Avengers: Endgame', 'Action', 'Anthony Russo, Joe Russo', 'Robert Downey Jr., Chris Evans', '2019', '181 min', '8.4'),
('The Silence of the Lambs', 'Thriller', 'Jonathan Demme', 'Jodie Foster, Anthony Hopkins', '1991', '118 min', '8.6'),
('The Green Mile', 'Drama', 'Frank Darabont', 'Tom Hanks, Michael Clarke Duncan', '1999', '189 min', '8.6'),
('Saving Private Ryan', 'War', 'Steven Spielberg', 'Tom Hanks, Matt Damon', '1998', '169 min', '8.6'),
('Braveheart', 'Drama', 'Mel Gibson', 'Mel Gibson, Sophie Marceau', '1995', '178 min', '8.4'),
('The Departed', 'Crime', 'Martin Scorsese', 'Leonardo DiCaprio, Matt Damon', '2006', '151 min', '8.5'),

('Joker', 'Drama', 'Todd Phillips', 'Joaquin Phoenix, Robert De Niro', '2019', '122 min', '8.4'),
('Parasite', 'Thriller', 'Bong Joon Ho', 'Song Kang-ho, Lee Sun-kyun', '2019', '132 min', '8.6'),
('12 Angry Men', 'Drama', 'Sidney Lumet', 'Henry Fonda, Lee J. Cobb', '1957', '96 min', '9.0'),
('The Social Network', 'Drama', 'David Fincher', 'Jesse Eisenberg, Andrew Garfield', '2010', '120 min', '7.8'),
('The Wolf of Wall Street', 'Comedy', 'Martin Scorsese', 'Leonardo DiCaprio, Jonah Hill', '2013', '180 min', '8.2'),
('The Imitation Game', 'Biography', 'Morten Tyldum', 'Benedict Cumberbatch, Keira Knightley', '2014', '113 min', '8.0'),
('Django Unchained', 'Western', 'Quentin Tarantino', 'Jamie Foxx, Christoph Waltz', '2012', '165 min', '8.4'),
('Whiplash', 'Drama', 'Damien Chazelle', 'Miles Teller, J.K. Simmons', '2014', '107 min', '8.5'),
('Mad Max: Fury Road', 'Action', 'George Miller', 'Tom Hardy, Charlize Theron', '2015', '120 min', '8.1'),
('The Revenant', 'Adventure', 'Alejandro G. Iñárritu', 'Leonardo DiCaprio, Tom Hardy', '2015', '156 min', '8.0'),

('Logan', 'Action', 'James Mangold', 'Hugh Jackman, Patrick Stewart', '2017', '137 min', '8.1'),
('Toy Story', 'Animation', 'John Lasseter', 'Tom Hanks, Tim Allen', '1995', '81 min', '8.3'),
('Up', 'Animation', 'Pete Docter', 'Ed Asner, Christopher Plummer', '2009', '96 min', '8.3'),
('Finding Nemo', 'Animation', 'Andrew Stanton, Lee Unkrich', 'Albert Brooks, Ellen DeGeneres', '2003', '100 min', '8.2'),
('Shrek', 'Animation', 'Andrew Adamson, Vicky Jenson', 'Mike Myers, Eddie Murphy', '2001', '90 min', '7.9'),
('Frozen', 'Animation', 'Chris Buck, Jennifer Lee', 'Kristen Bell, Idina Menzel', '2013', '102 min', '7.4'),
('Coco', 'Animation', 'Lee Unkrich, Adrian Molina', 'Anthony Gonzalez, Gael García Bernal', '2017', '105 min', '8.4'),
('Soul', 'Animation', 'Pete Docter, Kemp Powers', 'Jamie Foxx, Tina Fey', '2020', '100 min', '8.1'),
('Encanto', 'Animation', 'Jared Bush, Byron Howard', 'Stephanie Beatriz, María Cecilia Botero', '2021', '102 min', '7.3'),
('Zootopia', 'Animation', 'Byron Howard, Rich Moore', 'Ginnifer Goodwin, Jason Bateman', '2016', '108 min', '8.0');
